create table "ACCOUNT_HOLDER" (id integer generated by default as identity, http_image_link varbinary(255), name varchar(255), surname varchar(255), primary key (id));
//INSERT INTO ACCOUNT_HOLDER VALUES(0,"TEST","TEST","TEST");
